In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1=arr[2:6]

In [5]:
arr1

array([2, 3, 4, 5])

In [6]:
arr1[2:6]=4

In [7]:
arr1

array([2, 3, 4, 4])

In [8]:
arr

array([0, 1, 2, 3, 4, 4, 6, 7, 8, 9])

In [28]:
array2=np.arange(1,25).reshape(6,4)

In [29]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [30]:
arr2=array2[ 2 ,1:3 ]   #(rows,column-1)
arr2

array([10, 11])

In [31]:
arr2=array2[ : ,2 ]   #(rows,column-1)
arr2

array([ 3,  7, 11, 15, 19, 23])

In [36]:
array2[[1,4],[1,2]]

array([ 6, 19])

# Boolean indexing

In [43]:
names=np.array(['Bob','Will','amar','Bob','haseeb','shamikh','shamikh'])

In [47]:
data=np.random.randn(7,5)

In [49]:
data[names=='Bob']

array([[-0.64435148, -0.18419091,  2.44122374,  0.01724489,  0.71881854],
       [-0.00356247, -0.84389308, -0.5021744 , -0.26163778,  1.50094423]])

In [50]:
data

array([[-0.64435148, -0.18419091,  2.44122374,  0.01724489,  0.71881854],
       [ 0.77126863,  1.00497676,  1.51644831,  1.48057877, -1.39013166],
       [ 1.06263835, -0.12850609, -1.18235412, -0.55695086,  0.31150663],
       [-0.00356247, -0.84389308, -0.5021744 , -0.26163778,  1.50094423],
       [-0.12466502, -0.19927044, -0.37608673,  0.45606487,  1.99921747],
       [ 1.47037417, -0.47932947,  0.27922257,  1.41012633, -0.62829335],
       [ 0.15723497,  0.84132086,  0.80247806,  0.33701212, -2.48156661]])

In [51]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [54]:
data[0]

array([-0.64435148, -0.18419091,  2.44122374,  0.01724489,  0.71881854])

In [55]:
data[data>1]

array([2.44122374, 1.00497676, 1.51644831, 1.48057877, 1.06263835,
       1.50094423, 1.99921747, 1.47037417, 1.41012633])

In [64]:
data[names!='shamikh']=1.09

In [65]:
data

array([[ 1.09      ,  1.09      ,  1.09      ,  1.09      ,  1.09      ],
       [ 1.09      ,  1.09      ,  1.09      ,  1.09      ,  1.09      ],
       [ 1.09      ,  1.09      ,  1.09      ,  1.09      ,  1.09      ],
       [ 1.09      ,  1.09      ,  1.09      ,  1.09      ,  1.09      ],
       [ 1.09      ,  1.09      ,  1.09      ,  1.09      ,  1.09      ],
       [ 1.47037417, -0.47932947,  0.27922257,  1.41012633, -0.62829335],
       [ 0.15723497,  0.84132086,  0.80247806,  0.33701212, -2.48156661]])

In [67]:
array3=np.arange(1,33).reshape(8,4)

In [68]:
array3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [94]:
array3[[[1,2,2,7]],[:,[0,1,2,1]]]

SyntaxError: invalid syntax (<ipython-input-94-e406b8b34b5a>, line 1)

In [96]:
array3.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465, 496, 528], dtype=int32)

In [97]:
a={1,2,3,4,5,6,7,8}

In [100]:
s=set(a)

In [101]:
s

{1, 2, 3, 4, 5, 6, 7, 8}

In [102]:
arr3=np.arange(32)

In [103]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [118]:
arr3=arr3.reshape(4,8)

In [119]:
flat=arr3.flatten() #show 2d array as 1d
 flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [120]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [121]:
arr3=arr3.ravel()  

In [122]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [123]:
arr3=arr3.ravel() # converts 2d into 1d

In [124]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

# Concatenate

In [133]:
arr1=np.array([[7,8,9],[10,11,12]])

In [134]:
arr2=np.array([[1,2,3],[4,5,6]])

In [135]:
np.concatenate((arr1,arr2),axis=0)

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [140]:
np.concatenate((arr2,arr1),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [147]:
np.hstack((arr2,arr1))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [148]:
np.vstack((arr2,arr1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [149]:
## SPLIT

In [154]:
arr1=np.arange(1,13).reshape(4,3)

In [155]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
np.hsplit(arr1,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [167]:
np.vsplit(arr1,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [168]:
ar=np.arange(3)

In [169]:
ar.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [170]:
ar.repeat([1,3,4])

array([0, 1, 1, 1, 2, 2, 2, 2])