In [1]:
import numpy as np

In [15]:
arr=np.arange(10,501,10).reshape(10,5)

In [16]:
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [17]:
arr1=arr[:5,:]

In [18]:
arr1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [19]:
arr2=arr[[0,1,-2,-1], : ]
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [30]:
arr3=arr[::-2]
arr3

array([[ 10,  20,  30,  40,  50],
       [110, 120, 130, 140, 150],
       [210, 220, 230, 240, 250],
       [310, 320, 330, 340, 350],
       [410, 420, 430, 440, 450]])

In [31]:
arr3=arr[::-2,::-2]
arr3

array([[500, 480, 460],
       [400, 380, 360],
       [300, 280, 260],
       [200, 180, 160],
       [100,  80,  60]])

In [36]:
np.vsplit(arr,5)

[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]), array([[110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200]]), array([[210, 220, 230, 240, 250],
        [260, 270, 280, 290, 300]]), array([[310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400]]), array([[410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]])]

In [41]:
np.hsplit(arr,5)

[array([[ 10],
        [ 60],
        [110],
        [160],
        [210],
        [260],
        [310],
        [360],
        [410],
        [460]]), array([[ 20],
        [ 70],
        [120],
        [170],
        [220],
        [270],
        [320],
        [370],
        [420],
        [470]]), array([[ 30],
        [ 80],
        [130],
        [180],
        [230],
        [280],
        [330],
        [380],
        [430],
        [480]]), array([[ 40],
        [ 90],
        [140],
        [190],
        [240],
        [290],
        [340],
        [390],
        [440],
        [490]]), array([[ 50],
        [100],
        [150],
        [200],
        [250],
        [300],
        [350],
        [400],
        [450],
        [500]])]

In [46]:
np.stack(arr,axis=1)

array([[ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460],
       [ 20,  70, 120, 170, 220, 270, 320, 370, 420, 470],
       [ 30,  80, 130, 180, 230, 280, 330, 380, 430, 480],
       [ 40,  90, 140, 190, 240, 290, 340, 390, 440, 490],
       [ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]])

In [62]:
arr4=np.arange(1,25).reshape(2,3,4)
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [65]:
arr4[1][0][1]

14

In [66]:
arr4[1,2,0]

21

In [68]:
arr4[0,2,2:]

array([11, 12])

In [73]:
arr4[0,[1,2],[1,2]]

array([ 6, 11])

In [74]:
arr4[1,0,[1,2,3]]

array([14, 15, 16])

In [83]:
arr4[0,0:1,0:2 ]

array([[1, 2]])

In [85]:
arr4[1,0::2,0::2]

array([[13, 15],
       [21, 23]])

In [86]:
arr5=np.arange(100).reshape(4,5,5)

In [87]:
arr5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [ ]:
arr5[2:4,:,:]
