# 21/09/2019

In [1]:
import numpy as np

In [4]:
my_list = list(range(100000))
type(my_list)

list

In [6]:
my_arr = np.arange(100000)
type(my_arr)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10).ndim

1

In [8]:
%time
for _ in range(10):
    my_arr2 =my_arr =2

Wall time: 0 ns


In [9]:
data = np.random.randn(2,3)
data

array([[ 0.72770281,  0.10694988, -0.5086453 ],
       [ 2.07938148,  0.65888668, -0.01628771]])

In [22]:
data1 = np.random.randn(2,3,4)
data

array([[ 0.72770281,  0.10694988, -0.5086453 ],
       [ 2.07938148,  0.65888668, -0.01628771]])

In [21]:
data.ndim

2

In [12]:
data + data

array([[ 1.45540562,  0.21389975, -1.0172906 ],
       [ 4.15876297,  1.31777335, -0.03257542]])

In [13]:
data.shape

(2, 3)

In [23]:
np.dot(data,data1) #matrix multiplication

array([[[ 1.34034684, -0.75004971,  0.55791059, -0.09194146],
        [-0.08465907,  0.89629897,  1.27593593,  0.78972699]],

       [[ 2.78971819, -0.37365285,  1.46013228,  0.54307948],
        [-0.3744336 ,  1.66834109,  1.91049023,  0.99687138]]])

In [24]:
data @ data1 #matrix multiplication

array([[[ 1.34034684, -0.75004971,  0.55791059, -0.09194146],
        [ 2.78971819, -0.37365285,  1.46013228,  0.54307948]],

       [[-0.08465907,  0.89629897,  1.27593593,  0.78972699],
        [-0.3744336 ,  1.66834109,  1.91049023,  0.99687138]]])

In [25]:
data.dot(data1) #matrix multiplication, numpy func

array([[[ 1.34034684, -0.75004971,  0.55791059, -0.09194146],
        [-0.08465907,  0.89629897,  1.27593593,  0.78972699]],

       [[ 2.78971819, -0.37365285,  1.46013228,  0.54307948],
        [-0.3744336 ,  1.66834109,  1.91049023,  0.99687138]]])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.empty((2,3,2))

array([[[1.50664065e-312, 0.00000000e+000],
        [8.76794447e+252, 2.15895723e+227],
        [6.48224638e+170, 3.67145870e+228]],

       [[8.98886814e-096, 9.03292329e+271],
        [9.08366793e+223, 1.41075687e+232],
        [1.16070543e-028, 2.59933445e-306]]])

In [39]:
np.ones_like(data)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.zeros_like(data1)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [43]:
print(data.shape)
print(data.dtype)
np.ones_like(data)

(2, 3)
float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones((2,2) , dtype = 'uint8')

array([[1, 1],
       [1, 1]], dtype=uint8)

In [51]:
np.ones_like(data)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [53]:
np.full_like(data,5)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [55]:
arr1=np.array([1,2,3],dtype=np.float32)
arr1

array([1., 2., 3.], dtype=float32)

In [59]:
arr1=np.array([1,2.9,3],dtype='float32')
arr1

array([1. , 2.9, 3. ], dtype=float32)

In [62]:
arr1.dtype

dtype('float32')

In [63]:
arr1.astype(np.int)

array([1, 2, 3])

In [64]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [65]:
numeric_strings.astype(np.float)

array([ 1.25, -9.6 , 42.  ])

In [102]:
a1=np.random.rand(1,2)
a1

array([[0.73847601, 0.21919565]])

In [100]:
a2=np.random.rand(1,2)
a2

array([[0.48376309, 0.97103218]])

In [103]:
a1<a2

array([[False,  True]])

In [104]:
a1>a2

array([[ True, False]])

In [112]:
a=[1,2,3,4,5]

In [115]:
type(a[2])

TypeError: 'int' object is not callable

In [124]:
q=np.array([1,2,3,45,789]) #1 dimensational tensor(matrix)/6 dimensational vector

In [125]:
q.shape

(5,)

In [122]:
w=np.array([[2]]) #2 dimensational tensor(matrix)/1dimensation vector

In [123]:
w.shape

(1, 1)

In [126]:
w=np.array([[2,1]])

In [128]:
w.ndim

2

In [131]:
e=np.array([[[2]]])

In [132]:
e.ndim

3

In [133]:
e.shape

(1, 1, 1)

In [136]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
arr1[1:2,2:3]

array([[6]])

In [140]:
arr1[0:2,2:]

array([[2, 3],
       [6, 7]])

In [146]:
arr1[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [1]:
print('osama')

osama


In [3]:
name='osama'

In [4]:
print('My name is '+ name)

My name is osama


# 28/09/2019

In [1]:
import numpy as  np

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1:3]=5

In [7]:
arr

array([0, 5, 5, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1=np.arange(1,25).reshape(6,4)

In [27]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [22]:
arr1[2:5,2:]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [21]:
arr1[0:,2]

array([ 3,  7, 11, 15, 19, 23])

In [23]:
arr1[2:5,1]

array([10, 14, 18])

In [31]:
arr1[[2,4],[1,2]]

array([10, 19])

In [25]:
arr1[[1,4]] #one value is row

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [32]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [33]:
data=np.random.randn(7,4)

In [34]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [35]:
data

array([[-0.08885293, -0.51127273,  1.54376447, -2.04139673],
       [ 1.34988553,  0.294784  ,  0.22508134,  0.13836826],
       [ 0.13730542,  0.96380733, -0.7532532 , -0.69681231],
       [-1.78153465,  2.58011947,  0.32436066, -1.36438614],
       [-2.33630243,  0.41556267, -2.37326119,  1.07725991],
       [-1.16509963, -2.04142937, -0.24266524, -0.20370638],
       [ 0.78337993,  1.95526861, -0.95436004, -2.00850602]])

In [36]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [38]:
data[names=='Bob']

array([[-0.08885293, -0.51127273,  1.54376447, -2.04139673],
       [-1.78153465,  2.58011947,  0.32436066, -1.36438614]])

In [39]:
data[names=='Bob',2:]

array([[ 1.54376447, -2.04139673],
       [ 0.32436066, -1.36438614]])

In [40]:
data[names == 'Bob', 3]

array([-2.04139673, -1.36438614])

In [41]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [42]:
data[~(names == 'Bob')]

array([[ 1.34988553,  0.294784  ,  0.22508134,  0.13836826],
       [ 0.13730542,  0.96380733, -0.7532532 , -0.69681231],
       [-2.33630243,  0.41556267, -2.37326119,  1.07725991],
       [-1.16509963, -2.04142937, -0.24266524, -0.20370638],
       [ 0.78337993,  1.95526861, -0.95436004, -2.00850602]])

In [46]:
arr1[arr1>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr1[arr1>15]=2

In [49]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [50]:
arr = np.empty((8, 4))

In [52]:
for i in range(8):
    arr[i] = i

In [53]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [54]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [55]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [56]:
arr = np.arange(32).reshape((8, 4))

In [57]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [58]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [59]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [62]:
arr[[1, 5, 7, 2]][:, [0, 1,2,3]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [63]:
arr=np.arange(32)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [65]:
arr.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [69]:
flat1=arr.flatten()

In [74]:
ravel1=arr.ravel()
ravel1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [71]:
flat1[1]=100

In [72]:
flat1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31])

In [87]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr2=np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [86]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [91]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
#split
arr1=np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
np.vsplit(arr1,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [98]:
np.vsplit(arr1,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [99]:
np.hsplit(arr1,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [100]:
np.hsplit(arr1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# 05/10/2019 Absent

# 12/10/2019

In [2]:
import numpy as np
import pandas as pd

In [64]:
stdData={'math':[23,45,67,89,56],'physics':[13,32,95,34,77],'chemistry':[45,34,55,78,87],'computer science':[23,56,22,67,90]}
std=['nasir','mansoor','kashan','imad','shifa']
stdFrame=pd.DataFrame(stdData,index=std)
stdFrame

math  physics  chemistry  computer science
nasir      23       13         45                23
mansoor    45       32         34                56
kashan     67       95         55                22
imad       89       34         78                67
shifa      56       77         87                90

In [66]:
stdFrame['total']=stdFrame['math']+stdFrame['physics']+stdFrame['chemistry']+stdFrame['computer science']
stdFrame

math  physics  chemistry  computer science  total
nasir      23       13         45                23    104
mansoor    45       32         34                56    167
kashan     67       95         55                22    239
imad       89       34         78                67    268
shifa      56       77         87                90    310

In [67]:
stdFrame['status1']=['Fail'if num<200 else 'Pass'for num in stdFrame['total']]
stdFrame

math  physics  chemistry  computer science  total status1
nasir      23       13         45                23    104    Fail
mansoor    45       32         34                56    167    Fail
kashan     67       95         55                22    239    Pass
imad       89       34         78                67    268    Pass
shifa      56       77         87                90    310    Pass

In [68]:
stdFrame['per']=stdFrame['total']/3
stdFrame['per']=[str(i)+'%' for i in stdFrame['per']]
stdFrame

math  physics  chemistry  computer science  total status1  \
nasir      23       13         45                23    104    Fail   
mansoor    45       32         34                56    167    Fail   
kashan     67       95         55                22    239    Pass   
imad       89       34         78                67    268    Pass   
shifa      56       77         87                90    310    Pass   

                         per  
nasir    34.666666666666664%  
mansoor  55.666666666666664%  
kashan    79.66666666666667%  
imad      89.33333333333333%  
shifa    103.33333333333333%

In [69]:
stdFrame['status']=['Pass' if m>=33 and p>=33 and c>=33 and cs>33 else 'Fail'
    for m,p,c,cs in zip(stdFrame['math'],stdFrame['physics'],stdFrame['chemistry'],stdFrame['computer science'])]

In [70]:
stdFrame

math  physics  chemistry  computer science  total status1  \
nasir      23       13         45                23    104    Fail   
mansoor    45       32         34                56    167    Fail   
kashan     67       95         55                22    239    Pass   
imad       89       34         78                67    268    Pass   
shifa      56       77         87                90    310    Pass   

                         per status  
nasir    34.666666666666664%   Fail  
mansoor  55.666666666666664%   Fail  
kashan    79.66666666666667%   Fail  
imad      89.33333333333333%   Pass  
shifa    103.33333333333333%   Pass

In [71]:
stdFrame.T

nasir              mansoor  \
math                               23                   45   
physics                            13                   32   
chemistry                          45                   34   
computer science                   23                   56   
total                             104                  167   
status1                          Fail                 Fail   
per               34.666666666666664%  55.666666666666664%   
status                           Fail                 Fail   

                              kashan                imad                shifa  
math                              67                  89                   56  
physics                           95                  34                   77  
chemistry                         55                  78                   87  
computer science                  22                  67                   90  
total                            239                 268                  310  
status1                         Pass                Pass                 Pass  
per               79.66666666666667%  89.33333333333333%  103.33333333333333%  
status                          Fail                Pass                 Pass

In [106]:
del stdFrame["status1"]

In [107]:
stdFrame

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   
kashan           67       95         55                22    239   
imad             89       34         78                67    268   
shifa            56       77         87                90    310   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail  
kashan          79.66666666666667%   Fail  
imad            89.33333333333333%   Pass  
shifa          103.33333333333333%   Pass

In [108]:
print(stdFrame.columns)
print(stdFrame.index)

Index(['math', 'physics', 'chemistry', 'computer science', 'total', 'per',
       'status'],
      dtype='object', name='Subjects')
Index(['nasir', 'mansoor', 'kashan', 'imad', 'shifa'], dtype='object', name='Students Data')


In [109]:
stdFrame.index.name='Students Data'

In [110]:
stdFrame

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   
kashan           67       95         55                22    239   
imad             89       34         78                67    268   
shifa            56       77         87                90    310   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail  
kashan          79.66666666666667%   Fail  
imad            89.33333333333333%   Pass  
shifa          103.33333333333333%   Pass

In [111]:
stdFrame.columns.name='Subjects'

In [112]:
stdFrame

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   
kashan           67       95         55                22    239   
imad             89       34         78                67    268   
shifa            56       77         87                90    310   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail  
kashan          79.66666666666667%   Fail  
imad            89.33333333333333%   Pass  
shifa          103.33333333333333%   Pass

In [113]:
stdFrame.math

Students Data
nasir      23
mansoor    45
kashan     67
imad       89
shifa      56
Name: math, dtype: int64

In [114]:
stdFrame.status

Students Data
nasir      Fail
mansoor    Fail
kashan     Fail
imad       Pass
shifa      Pass
Name: status, dtype: object

In [115]:
stdFrame['computer science']

Students Data
nasir      23
mansoor    56
kashan     22
imad       67
shifa      90
Name: computer science, dtype: int64

In [116]:
for i in stdFrame.columns:
    if'computer science' in i:
        print('true')
        
    

true


In [117]:
'computer science' in stdFrame.columns

True

In [118]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])


In [119]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [120]:
obj3.reindex(range(9), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
6    yellow
7    yellow
8    yellow
dtype: object

In [121]:
obj2 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 5, 15])
obj2

0       blue
5     purple
15    yellow
dtype: object

In [122]:
obj2.reindex(range(20),method='ffill')

0       blue
1       blue
2       blue
3       blue
4       blue
5     purple
6     purple
7     purple
8     purple
9     purple
10    purple
11    purple
12    purple
13    purple
14    purple
15    yellow
16    yellow
17    yellow
18    yellow
19    yellow
dtype: object

In [123]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
         index=['a', 'c', 'd'],
        columns=['Ohio', 'Texas', 'California'])

In [124]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [125]:
frame = pd.DataFrame(np.arange(100).reshape((20, 5)),
    columns=['Ohio', 'Texas', 'California','NYC','Chicago'])
frame

Ohio  Texas  California  NYC  Chicago
0      0      1           2    3        4
1      5      6           7    8        9
2     10     11          12   13       14
3     15     16          17   18       19
4     20     21          22   23       24
5     25     26          27   28       29
6     30     31          32   33       34
7     35     36          37   38       39
8     40     41          42   43       44
9     45     46          47   48       49
10    50     51          52   53       54
11    55     56          57   58       59
12    60     61          62   63       64
13    65     66          67   68       69
14    70     71          72   73       74
15    75     76          77   78       79
16    80     81          82   83       84
17    85     86          87   88       89
18    90     91          92   93       94
19    95     96          97   98       99

In [126]:
frame = pd.DataFrame(np.arange(50).reshape((10, 5)),
        index=range(0,50,5),
        columns=['Ohio', 'Texas', 'California','NYC','Chicago'])
frame

Ohio  Texas  California  NYC  Chicago
0      0      1           2    3        4
5      5      6           7    8        9
10    10     11          12   13       14
15    15     16          17   18       19
20    20     21          22   23       24
25    25     26          27   28       29
30    30     31          32   33       34
35    35     36          37   38       39
40    40     41          42   43       44
45    45     46          47   48       49

In [127]:
stdFrame.loc['nasir']

Subjects
math                                 23
physics                              13
chemistry                            45
computer science                     23
total                               104
per                 34.666666666666664%
status                             Fail
Name: nasir, dtype: object

In [129]:
stdFrame.loc['Yasir']=[45,32,21,67]

ValueError: cannot set a row with mismatched columns

In [130]:
stdFrame.iloc[0:2]

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail

In [137]:
stdFrame.loc['nasir':'kashan']

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   
kashan           67       95         55                22    239   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail  
kashan          79.66666666666667%   Fail

In [138]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [139]:
new_obj = obj.drop('c')

In [141]:
obj.fillna(3)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [144]:
stdFrame['math']

Students Data
nasir      23
mansoor    45
kashan     67
imad       89
shifa      56
Name: math, dtype: int64

In [148]:
stdFrame[(stdFrame['physics']>60)&stdFrame['math']>40]

Empty DataFrame
Columns: [math, physics, chemistry, computer science, total, per, status]
Index: []

In [152]:
stdFrame

Subjects       math  physics  chemistry  computer science  total  \
Students Data                                                      
nasir            23       13         45                23    104   
mansoor          45       32         34                56    167   
kashan           67       95         55                22    239   
imad             89       34         78                67    268   
shifa            56       77         87                90    310   

Subjects                       per status  
Students Data                              
nasir          34.666666666666664%   Fail  
mansoor        55.666666666666664%   Fail  
kashan          79.66666666666667%   Fail  
imad            89.33333333333333%   Pass  
shifa          103.33333333333333%   Pass

In [154]:
del stdFrame['status']

In [167]:
del stdFrame['per']

KeyError: 'per'

In [158]:
stdFrame[stdFrame>33]='Pass'

In [159]:
stdFrame

Subjects       math physics chemistry computer science total
Students Data                                               
nasir            23      13      Pass               23  Pass
mansoor        Pass      32      Pass             Pass  Pass
kashan         Pass    Pass      Pass               22  Pass
imad           Pass    Pass      Pass             Pass  Pass
shifa          Pass    Pass      Pass             Pass  Pass

In [163]:
del stdFrame['total']

In [166]:
stdFrame

Subjects       math physics chemistry computer science
Students Data                                         
nasir            23      13      Pass               23
mansoor        Pass      32      Pass             Pass
kashan         Pass    Pass      Pass               22
imad           Pass    Pass      Pass             Pass
shifa          Pass    Pass      Pass             Pass

In [165]:
f = lambda x: x.max() - x.min()
stdFrame.apply(f)

TypeError: ("'>=' not supported between instances of 'int' and 'str'", 'occurred at index math')

# 19/10/2019

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data.csv')

In [11]:
data.head()

Student Code  Degree     Student Name  Mid  Quiz 1  Quiz 2  \
0   022-14-19987  BS(CS)      Abdul Basit   28     8.0     3.0   
1  022-14-110233  BS(CS)      Adeel Ahmed   17     NaN     5.0   
2  022-14-110585  BS(CS)     Afrah Zareen   18     5.0     2.0   
3   022-14-19718  BS(CS)   Ahmed Ali Raza   14     7.0     2.0   
4  022-14-110648  BS(CS)  Ahsan Ali Vohra   27     7.0     6.0   

   Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0                8           7.0           9.0                    9   
1                5           8.0          10.0                   10   
2                5           8.0          10.0                   10   
3                7           NaN           2.0                    2   
4                7           7.0           9.0                    9   

   Total Sessional (50)  Final (50)  Total (100) Grade  
0                    45        25.0           70     B  
1                    32        18.0           50     F  
2                    33        30.0           63     C  
3                    23        23.0           46     F  
4                    43        34.0           77     B

In [6]:
data.iloc[9]

Student Code            022-14-110599
Degree                         BS(CS)
Student Name                  Arsalan
Mid                                28
Quiz 1                              8
Quiz 2                              6
Best of Quizzes                     8
Assignment 1                        8
Assignment 2                      NaN
Best of Assignments                 8
Total Sessional (50)               44
Final (50)                         40
Total (100)                        84
Grade                               A
Name: 9, dtype: object

In [3]:
data

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
3      2.0                7           NaN           2.0   

In [14]:
data[data['Assignment 1']>=7]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
4      6.0                7           7.0           9.0                    9   
5      6.0                9           8.0          10.0                   10   
6      6.0                6           8.0          10.0                   10   
7      6.0                9           8.0          10.0                   10   
8      4.0                9           7.0           9.0                    9   
9      6.0                8           8.0           NaN                    8   
10     7.0                8           8.0           NaN                    8   
12     5.0                7           8.0          10.0                   10   
13     4.0                8           8.0          10.0                   10   
16     5.0                5           7.0           9.0                    9  

In [15]:
[data['Assignment 1']>=7]

[0      True
 1      True
 2      True
 3     False
 4      True
 5      True
 6      True
 7      True
 8      True
 9      True
 10     True
 11    False
 12     True
 13     True
 14    False
 15    False
 16     True
 17     True
 18     True
 19     True
 20     True
 21     True
 22     True
 23     True
 24     True
 25     True
 26    False
 27     True
 28     True
 29    False
 30     True
 31     True
 32     True
 33     True
 34     True
 35    False
 36     True
 37     True
 38    False
 39     True
 40     True
 41     True
 42     True
 43    False
 44     True
 45     True
 46     True
 47    False
 Name: Assignment 1, dtype: bool]

In [16]:
data[data['Assignment 2']>=8]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
4      6.0                7           7.0           9.0                    9   
5      6.0                9           8.0          10.0                   10   
6      6.0                6           8.0          10.0                   10   
7      6.0                9           8.0          10.0                   10   
8      4.0                9           7.0           9.0                    9   
12     5.0                7           8.0          10.0                   10   
13     4.0                8           8.0          10.0                   10   
14     4.0                7           6.0           8.0                    8   
16     5.0                5           7.0           9.0                    9   
17     5.0                8           9.0          11.0                   11   
18     2.0                5           8.0          10.0                   10   
19     6.0                9           8.0          10.0                   10   
20     6.0                7           7.0           9.0                    9   
21     6.0                9           9.0          11.0                   11   
23     NaN                5           8.0       

In [20]:
data[data['Assignment 1']>=7].count()

Student Code            38
Degree                  38
Student Name            38
Mid                     38
Quiz 1                  36
Quiz 2                  37
Best of Quizzes         38
Assignment 1            38
Assignment 2            29
Best of Assignments     38
Total Sessional (50)    38
Final (50)              38
Total (100)             38
Grade                   38
dtype: int64

In [21]:
data[data['Assignment 1' and 'Assignment 2']>=7].count()

Student Code            35
Degree                  35
Student Name            35
Mid                     35
Quiz 1                  33
Quiz 2                  33
Best of Quizzes         35
Assignment 1            34
Assignment 2            35
Best of Assignments     35
Total Sessional (50)    35
Final (50)              35
Total (100)             35
Grade                   35
dtype: int64

In [26]:
data[(data['Assignment 1']>=7) & (data['Assignment 2']>=7) & (data['Best of Assignments']>=7)]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
4      6.0                7           7.0           9.0                    9   
5      6.0                9           8.0          10.0                   10   
6      6.0                6           8.0          10.0                   10   
7      6.0                9           8.0          10.0                   10   
8      4.0                9           7.0           9.0                    9   
12     5.0                7           8.0          10.0                   10   
13     4.0                8           8.0          10.0                   10   
16     5.0                5           7.0           9.0                    9   
17     5.0                8           9.0          11.0                   11   
18     2.0                5           8.0          10.0                   10   
19     6.0                9           8.0          10.0                   10   
20     6.0                7           7.0           9.0                    9   
21     6.0                9           9.0          11.0                   11   
23     NaN                5           8.0          10.0                   10   
24     4.0                5           9.0          11.0                   11   
25     6.0                9           8.0          10.0                   10   
27     6.0                8           8.0          10.0                   10   
28     6.0                6           9.0          11.0                   11   
32     2.0              

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 14 columns):
Student Code            48 non-null object
Degree                  48 non-null object
Student Name            48 non-null object
Mid                     48 non-null int64
Quiz 1                  45 non-null float64
Quiz 2                  45 non-null float64
Best of Quizzes         48 non-null int64
Assignment 1            45 non-null float64
Assignment 2            36 non-null float64
Best of Assignments     48 non-null int64
Total Sessional (50)    48 non-null int64
Final (50)              47 non-null float64
Total (100)             48 non-null int64
Grade                   48 non-null object
dtypes: float64(5), int64(5), object(4)
memory usage: 4.5+ KB


In [29]:
data.describe()

Mid     Quiz 1     Quiz 2  Best of Quizzes  Assignment 1  \
count  48.000000  45.000000  45.000000        48.000000     45.000000   
mean   22.937500   7.288889   4.866667         7.020833      7.755556   
std     5.236558   1.561209   1.455397         1.973113      1.170772   
min     9.000000   4.000000   1.000000         0.000000      5.000000   
25%    20.000000   6.000000   4.000000         6.000000      7.000000   
50%    25.000000   8.000000   5.000000         7.000000      8.000000   
75%    27.000000   9.000000   6.000000         9.000000      8.000000   
max    30.000000   9.000000   7.000000         9.000000     10.000000   

       Assignment 2  Best of Assignments  Total Sessional (50)  Final (50)  \
count     36.000000            48.000000             48.000000   47.000000   
mean       9.444444             8.937500             38.895833   27.851064   
std        1.629100             2.127892              7.179283    8.431253   
min        2.000000             0.000000             18.000000    8.000000   
25%        9.000000             8.750000             36.750000   22.500000   
50%       10.000000            10.000000             41.000000   28.000000   
75%       10.000000            10.000000             44.000000   33.500000   
max       11.000000            11.000000             46.000000   45.000000   

       Total (100)  
count    48.000000  
mean     66.166667  
std      15.227821  
min      18.000000  
25%      60.000000  
50%      69.000000  
75%      75.250000  
max      91.000000

In [30]:
data[(data['Assignment 1']>=7) & (data['Assignment 2']>=7)]['Student Name']

0                        Abdul Basit
1                        Adeel Ahmed
2                       Afrah Zareen
4                    Ahsan Ali Vohra
5                        Ameer Hamza
6                      Anas Ali Khan
7                   Aneebullah Niazi
8                     Areesha Sohail
12               Hafiza Tooba Akbani
13                Hamza Abdul Jabbar
16                      Hassam Ahmed
17                      Khalid Anwer
18                     Madiha Jabeen
19                   Mohammad Hunain
20                    Muhammad Aamir
21    Muhammad Abdul Rehman Siddiqui
23                Muhammad Ali Iqbal
24                    Muhammad Bilal
25                    Muhammad Faraz
27               Muhammad Osama Khan
28            Muhammad Saqib Intizar
32             Muhammad Wajahat Khan
33              Muhammad Younus Baig
34                  Nazeer Bin Zafar
39                       Sania Iqbal
40                       Sharif Taqi
41                     Shariqa Ahmad
4

In [49]:
data[(data['Assignment 1']>=7) & (data['Assignment 2']>=7) & 
     (data['Student Name'].str.startswith("Muhammad")) | 
     (data['Student Name'].str.startswith("Mohammad"))]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
19     6.0                9           8.0          10.0                   10   
20     6.0                7           7.0           9.0                    9   
21     6.0                9           9.0          11.0                   11   
23     NaN                5           8.0          10.0                   10   
24     4.0                5           9.0          11.0                   11   
25     6.0                9           8.0          10.0                   10   
27     6.0                8           8.0          10.0                   10   
28     6.0                6           9.0          11.0                   11   
32     2.0                2           8.0          10.0                   10   
33     2.0                4           8.0          10.0                   10   

    Total Sessional (50)  Final (50)  Total (100) Grade  
19                    46        45.0           91     A  
20                    40        31.0           71     B  
21                    40        20.0           60     C  
23                    41        21.0           62     C  
24                    44        33.0           77     B  
25                    45        41.0           86     A  
27                    45        26.0           71     B  
28                    39        18.0           57     F  
32                    21         8.0           29     F  
33                    34        17.0           51     F

In [59]:
obj = pd.Series(range(6),index=['d','a','b','c','1','A'])

In [78]:
frame= pd.DataFrame(np.arange(24).reshape((4,6)),index=['three','one','1','A'],
columns=['d','a','b','c','1','A'])

In [79]:
frame.sort_index()

d   a   b   c   1   A
1      12  13  14  15  16  17
A      18  19  20  21  22  23
one     6   7   8   9  10  11
three   0   1   2   3   4   5

In [80]:
obj.sort_index()

1    4
A    5
a    1
b    2
c    3
d    0
dtype: int64

In [81]:
obj.sort_values()

d    0
a    1
b    2
c    3
1    4
A    5
dtype: int64

In [82]:
chr(65) #ASCII

'A'

In [83]:
frame

d   a   b   c   1   A
three   0   1   2   3   4   5
one     6   7   8   9  10  11
1      12  13  14  15  16  17
A      18  19  20  21  22  23

In [84]:
frame.sort_index(axis=1,inplace=True)

In [85]:
frame

1   A   a   b   c   d
three   4   5   1   2   3   0
one    10  11   7   8   9   6
1      16  17  13  14  15  12
A      22  23  19  20  21  18

In [86]:
frame.sort_index(axis=1,ascending=False)

d   c   b   a   A   1
three   0   3   2   1   5   4
one     6   9   8   7  11  10
1      12  15  14  13  17  16
A      18  21  20  19  23  22

In [90]:
frame.sort_values(by='A',ascending=False)

1   A   a   b   c   d
A      22  23  19  20  21  18
1      16  17  13  14  15  12
one    10  11   7   8   9   6
three   4   5   1   2   3   0

In [94]:
data.sort_values(by=["Mid",'Best of Quizzes'])

Student Code  Degree                    Student Name  Mid  Quiz 1  \
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
32     2.0                2           8.0          10.0                   10   
38     6.0                6           5.0           7.0                    7   
47     5.0                9           5.0           7.0                    7   
3      2.0                7           NaN           2.0   

In [96]:
data.sort_values(by=['Best of Quizzes',"Mid"])

Student Code  Degree                    Student Name  Mid  Quiz 1  \
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
15     NaN                0           NaN           NaN                    0   
32     2.0                2           8.0          10.0                   10   
33     2.0                4           8.0          10.0                   10   
39     4.0                4           9.0          11.0   

In [106]:
data.sort_values(by=['Total (100)','Best of Quizzes',"Mid"],ascending=False)

Student Code  Degree                    Student Name  Mid  Quiz 1  \
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0   
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0   
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0   
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
19     6.0                9           8.0          10.0                   10   
10     7.0                8           8.0           NaN                    8   
25     6.0                9           8.0          10.0                   10   
34     6.0                9           8.0          10.0   

In [115]:
obj=pd.Series([7,-5,7,4,4,6,0,2])
obj.sort_values(inplace=True)
obj

1   -5
6    0
7    2
3    4
4    4
5    6
0    7
2    7
dtype: int64

In [116]:
obj.rank(method='first')

1    1.0
6    2.0
7    3.0
3    4.0
4    5.0
5    6.0
0    7.0
2    8.0
dtype: float64

In [117]:
data['Mid'].idxmax()

10

In [121]:
data['Mid']

0     28
1     17
2     18
3     14
4     27
5     25
6     28
7     26
8     19
9     28
10    30
11    28
12    23
13    24
14    21
15    18
16    23
17    20
18    16
19    27
20    24
21    20
22    20
23    26
24    28
25    26
26    27
27    27
28    22
29    17
30    23
31    27
32     9
33    20
34    25
35    20
36    25
37    27
38     9
39    28
40    27
41    20
42    28
43    28
44    25
45    27
46    25
47    11
Name: Mid, dtype: int64

In [122]:
data['Mid'][9]

28

In [124]:
data['Mid','Best of Quizzes']

KeyError: ('Mid', 'Best of Quizzes')

In [126]:
frame

1   A   a   b   c   d
three   4   5   1   2   3   0
one    10  11   7   8   9   6
1      16  17  13  14  15  12
A      22  23  19  20  21  18

In [125]:
frame.cumsum()

1   A   a   b   c   d
three   4   5   1   2   3   0
one    14  16   8  10  12   6
1      30  33  21  24  27  18
A      52  56  40  44  48  36

In [129]:
frame

1   A   a   b   c   d
three   4   5   1   2   3   0
one    10  11   7   8   9   6
1      16  17  13  14  15  12
A      22  23  19  20  21  18

In [131]:
frame['A'].isin(['5'])

three     True
one      False
1        False
A        False
Name: A, dtype: bool

In [134]:
data[data['Assignment 1'].isin([8,9])]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN   
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0   
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN   
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0   
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0   
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
1      5.0                5           8.0          10.0                   10   
2      2.0                5           8.0          10.0                   10   
5      6.0                9           8.0          10.0                   10   
6      6.0                6           8.0          10.0                   10   
7      6.0                9           8.0          10.0                   10   
9      6.0                8           8.0           NaN                    8   
10     7.0                8           8.0           NaN                    8   
12     5.0                7           8.0          10.0                   10   
13     4.0                8           8.0          10.0                   10   
17     5.0                8           9.0          11.0                   11   
18     2.0                5           8.0          10.0                   10   
19     6.0                9           8.0          10.0                   10   
21     6.0                9           9.0          11.0                   11   
23     NaN                5           8.0          10.0                   10   
24     4.0                5           9.0          11.0                   11   
25     6.0                9           8.0          10.0                   10   
27     6.0                8           8.0          10.0                   10   
28     6.0                6           9.0          11.0                   11   
30     6.0                8           9.0           NaN                    9   
32     2.0                2         

In [135]:
data[data['Assignment 1'].isin(['Muhammad'])]

Empty DataFrame
Columns: [Student Code, Degree, Student Name, Mid, Quiz 1, Quiz 2, Best of Quizzes, Assignment 1, Assignment 2, Best of Assignments, Total Sessional (50), Final (50), Total (100), Grade]
Index: []

# 26/10/2019

In [ ]:
import os


# 02/11/2019

# Interacting with Web APIs

In [1]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [2]:
data = resp.json()

In [4]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29335',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29335/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29335/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29335/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/29335',
  'id': 516487611,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzM1NzM4MjQz',
  'number': 29335,
  'title': 'Remove FrozenNDArray',
  'user': {'login': 'WillAyd',
   'id': 609873,
   'node_id': 'MDQ6VXNlcjYwOTg3Mw==',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/609873?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/WillAyd',
   'html_url': 'https://github.com/WillAyd',
   'followers_url': 'https://api.github.com/users/WillAyd/followers',
   'following_url': 'https://api.github.com/users/WillAyd

In [3]:
data[0]['title']

'Remove FrozenNDArray'

In [7]:
import pandas as pd

In [10]:
issues = pd.DataFrame(data, columns=['number', 'title','labels', 'state'])


In [11]:
issues.head

<bound method NDFrame.head of     number                                              title  \
0    29335                               Remove FrozenNDArray   
1    29334  BUG: assignment to multiple columns when some ...   
2    29333                              CLN: type annotations   
3    29332  maybe_upcast_putmask: require other to be a sc...   
4    29331                REF: implement maybe_promote_scalar   
5    29330  conda env create --file environment.yaml Fails...   
6    29329                  WEB: Fix extension of about/index   
7    29328  TO_CSV Compression with dict arguement release...   
8    29327                      CLN: fix mypy warnings/errors   
9    29326  df.to_hdf with mode='a' fails on external driv...   
10   29325           WEB: about/index has the extension wrong   
11   29323  pd.Series.apply can't be made to produce Serie...   
12   29322                                   release gil more   
13   29321  Pandas dataframe sub-setting returns NaN's whe..

In [12]:
issues

number                                              title  \
0    29335                               Remove FrozenNDArray   
1    29334  BUG: assignment to multiple columns when some ...   
2    29333                              CLN: type annotations   
3    29332  maybe_upcast_putmask: require other to be a sc...   
4    29331                REF: implement maybe_promote_scalar   
5    29330  conda env create --file environment.yaml Fails...   
6    29329                  WEB: Fix extension of about/index   
7    29328  TO_CSV Compression with dict arguement release...   
8    29327                      CLN: fix mypy warnings/errors   
9    29326  df.to_hdf with mode='a' fails on external driv...   
10   29325           WEB: about/index has the extension wrong   
11   29323  pd.Series.apply can't be made to produce Serie...   
12   29322                                   release gil more   
13   29321  Pandas dataframe sub-setting returns NaN's whe...   
14   29320  Unable to install pandas on python 3.8 [Window...   
15   29317      fix bugs cause replacer's dtype not respected   
16   29315                      Fix SS03 Issues in Docstrings   
17   29314                             CLN: assorted cleanups   
18   29311  PERF: regression in MultiIndex get_loc indexin...   
19   29310                   HDF file compression not working   
20   29309  API: how to create a "shallow copy" of a DataF...   
21   29305     CLN: tighten Exception catching in indexing.py   
22   29298                CLN: unnecessary exception catching   
23   29297     TypeError when setting MultiIndex in DataFrame   
24   29293  Implement safe_ea_cast to avoid catching Excep...   
25   29290                 Unexpected behaviour of uint dtype   
26   29288           Fix missing tick labels on twinned axes.   
27   29284  combination of groupby & nlargest gives differ...   
28   29282  Inconsistency of copy and selection methods of...   
29   29279  DataFrame.replace: TypeError: “Cannot compare ...   

                                               labels state  
0   [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
1                                                  []  open  
2   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 1508144531, 'node_id': 'MDU6TGFiZWwxNT...  open  
7   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
8   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
9   [{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
10  [{'id': 1508144531, 'node_id': 'MDU6TGFiZWwxNT...  open  
11                                                 []  open  
12  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
13                                                 []  open  
14  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
15                                                 []  open  
16  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
17                                                 []  open  
18  [{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2...  open  
19  [{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
20  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
21  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
22  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
23  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
24  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzM...  open  
27  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
28                                                 []  open  
29  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open

In [13]:
import sqlite3

In [14]:
query = """CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER);"""

In [15]:
con = sqlite3.connect('mydata.sqlite')

In [16]:
con.execute(query)

In [17]:
con.commit()

In [18]:
data = [('Atlanta', 'Georgia', 1.25, 6),
('Tallahassee', 'Florida', 2.6, 3),
('Sacramento', 'California', 1.7, 5)]

In [19]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [20]:
con.executemany(stmt, data)

In [21]:
con.commit()

In [22]:
cursor = con.execute('select * from test')

In [23]:
rows = cursor.fetchall()

In [24]:
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [25]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [26]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [27]:
import sqlalchemy as sqla

In [28]:
db = sqla.create_engine('sqlite:///mydata.sqlite')

In [29]:
pd.read_sql('select * from test', db)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

# Chapter 7 Data Cleaning & Preparation

In [32]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [33]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [34]:
string_data[0] = None

In [35]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [36]:
from numpy import nan as NA

In [37]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [38]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [42]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [43]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [45]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  1.413488       NaN       NaN
1 -1.298962       NaN       NaN
2  0.960114       NaN -0.442769
3  0.692543       NaN -0.757497
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [46]:
df.dropna()

0         1         2
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [47]:
df.dropna(thresh=2)

0         1         2
2  0.960114       NaN -0.442769
3  0.692543       NaN -0.757497
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [48]:
df.fillna(0)

0         1         2
0  1.413488  0.000000  0.000000
1 -1.298962  0.000000  0.000000
2  0.960114  0.000000 -0.442769
3  0.692543  0.000000 -0.757497
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [49]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  1.413488  0.500000  0.000000
1 -1.298962  0.500000  0.000000
2  0.960114  0.500000 -0.442769
3  0.692543  0.500000 -0.757497
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [50]:
_ = df.fillna(0, inplace=True)

In [51]:
df

0         1         2
0  1.413488  0.000000  0.000000
1 -1.298962  0.000000  0.000000
2  0.960114  0.000000 -0.442769
3  0.692543  0.000000 -0.757497
4 -0.970971  1.822775 -0.836719
5 -0.624342  1.921926  1.996391
6 -0.129170 -0.070637  1.361226

In [56]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  1.019318  0.661217  0.923853
1  0.351507  0.333923  0.339416
2  0.483543       NaN  0.139855
3 -1.230992       NaN  0.820506
4 -0.797990       NaN       NaN
5  1.160599       NaN       NaN

In [57]:
df.fillna(method='ffill')

0         1         2
0  1.019318  0.661217  0.923853
1  0.351507  0.333923  0.339416
2  0.483543  0.333923  0.139855
3 -1.230992  0.333923  0.820506
4 -0.797990  0.333923  0.820506
5  1.160599  0.333923  0.820506

In [58]:
df.fillna(method='ffill', limit=2)

0         1         2
0  1.019318  0.661217  0.923853
1  0.351507  0.333923  0.339416
2  0.483543  0.333923  0.139855
3 -1.230992  0.333923  0.820506
4 -0.797990       NaN  0.820506
5  1.160599       NaN  0.820506

In [59]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [61]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [62]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
....: 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [63]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [64]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [65]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [67]:
data['v1'] = range(7)


In [68]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [69]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [70]:
data.drop_duplicates(['k1'], keep='last')

k1  k2  v1
4  one   3   4
6  two   4   6

# 09/11/2019

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
'Pastrami', 'corned beef', 'Bacon',
'pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [4]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [5]:
meat_to_animal = {'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'}


In [6]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [9]:
data['animal'] = lowercased.map(meat_to_animal)

In [7]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [11]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [8]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [9]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [10]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [15]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [11]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [12]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [13]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])

In [14]:
transform = lambda x: x[:4].upper()

In [16]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [17]:
data.index = data.index.map(transform)

In [18]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [23]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [19]:
data.rename(index={'OHIO': 'INDIANA'},
columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [20]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [21]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [41]:
ages = [18,20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] #Ages

In [29]:
bins = [18, 25, 35,45, 60, 100] # Ranges

In [30]:
cats = pd.cut(ages, bins)#Range of each age

In [31]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 45], (35, 45], (25, 35]]
Length: 12
Categories (5, interval[int64]): [(18, 25] < (25, 35] < (35, 45] < (45, 60] < (60, 100]]

In [32]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 4, 2, 2, 1], dtype=int8)

In [34]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 45], (45, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [39]:
pd.value_counts(cats)

(18, 25]     5
(35, 45]     3
(25, 35]     3
(60, 100]    1
(45, 60]     0
dtype: int64

In [52]:
pd.cut(ages,[18, 25, 35,45, 60, 100],right=False)

[[18, 25), [18, 25), [18, 25), [25, 35), [25, 35), ..., [25, 35), [60, 100), [45, 60), [35, 45), [25, 35)]
Length: 13
Categories (5, interval[int64]): [[18, 25) < [25, 35) < [35, 45) < [45, 60) < [60, 100)]

In [54]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 45], (45, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [65]:
groups=['Youth','YoundAdult','Middleaged','Senior']

In [66]:
pd.cut(ages,[18, 25, 35,45, 60],labels=groups)

[NaN, Youth, Youth, Youth, YoundAdult, ..., YoundAdult, NaN, Middleaged, Middleaged, YoundAdult]
Length: 13
Categories (4, object): [Youth < YoundAdult < Middleaged < Senior]

In [68]:
data=np.random.rand(20)
data

array([0.07926945, 0.10501538, 0.75021893, 0.27162897, 0.76372313,
       0.5635123 , 0.91670055, 0.60242896, 0.67453467, 0.4356986 ,
       0.55499632, 0.01598705, 0.54597261, 0.49709019, 0.31834451,
       0.89509432, 0.58834734, 0.66037482, 0.34839106, 0.9924327 ])

In [72]:
catt=pd.cut(data,3,precision=2)
catt

[(0.015, 0.34], (0.015, 0.34], (0.67, 0.99], (0.015, 0.34], (0.67, 0.99], ..., (0.67, 0.99], (0.34, 0.67], (0.34, 0.67], (0.34, 0.67], (0.67, 0.99]]
Length: 20
Categories (3, interval[float64]): [(0.015, 0.34] < (0.34, 0.67] < (0.67, 0.99]]

In [73]:
pd.value_counts(catt)

(0.34, 0.67]     9
(0.67, 0.99]     6
(0.015, 0.34]    5
dtype: int64

In [78]:
data1=np.random.rand(1000)
data1[:10]

array([0.16523167, 0.78677398, 0.60534576, 0.46053514, 0.4489581 ,
       0.61499396, 0.26687914, 0.80047796, 0.2565039 , 0.65250372])

In [79]:
catt1=pd.cut(data1,4)
catt1

[(-0.00064, 0.25], (0.75, 0.999], (0.5, 0.75], (0.25, 0.5], (0.25, 0.5], ..., (0.75, 0.999], (-0.00064, 0.25], (-0.00064, 0.25], (0.5, 0.75], (-0.00064, 0.25]]
Length: 1000
Categories (4, interval[float64]): [(-0.00064, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 0.999]]

In [80]:
pd.value_counts(catt1)

(0.25, 0.5]         263
(0.75, 0.999]       254
(-0.00064, 0.25]    252
(0.5, 0.75]         231
dtype: int64

# Detecting and Filtering Outliers

In [82]:
import pandas as pd
import numpy as npp
data=pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.023526    -0.019550     0.070084    -0.000371
std       0.984314     0.957160     0.957627     1.011701
min      -3.053554    -2.831117    -2.829426    -3.097877
25%      -0.677094    -0.678618    -0.572104    -0.693629
50%       0.097892    -0.016354     0.066463     0.007349
75%       0.698402     0.606340     0.723016     0.670883
max       3.469092     3.305010     2.572957     3.437974

In [83]:
col=data[2]

In [86]:
col[np.abs(col)>2]

8     -2.052298
29    -2.084008
31     2.349485
41     2.491858
86    -2.049349
99     2.427851
128    2.113105
133   -2.514232
183   -2.512000
259    2.088307
268   -2.090042
311    2.055166
315    2.101416
331    2.293748
349    2.267206
445   -2.395364
502   -2.094583
504   -2.164151
517   -2.073163
537    2.572957
581   -2.247439
590    2.136671
627    2.214091
671   -2.829426
700    2.241067
741   -2.236854
744    2.227640
761   -2.508067
807   -2.747382
848    2.187847
888    2.342956
894    2.329927
915   -2.078668
928   -2.482334
932    2.476604
939   -2.498013
941    2.046523
Name: 2, dtype: float64

In [90]:
data.head()

0         1         2         3
0  0.859192 -0.411535  0.983757  2.139135
1  0.691693  1.895633  1.359774 -0.073916
2 -0.390728  0.322815  0.622371 -0.066702
3 -0.868063 -0.020363  0.577020 -1.935676
4  0.339624 -0.899649 -0.542342 -0.568619

In [99]:
data[(np.abs(data)>3)]

0   1   2   3
0   NaN NaN NaN NaN
1   NaN NaN NaN NaN
2   NaN NaN NaN NaN
3   NaN NaN NaN NaN
4   NaN NaN NaN NaN
5   NaN NaN NaN NaN
6   NaN NaN NaN NaN
7   NaN NaN NaN NaN
8   NaN NaN NaN NaN
9   NaN NaN NaN NaN
10  NaN NaN NaN NaN
11  NaN NaN NaN NaN
12  NaN NaN NaN NaN
13  NaN NaN NaN NaN
14  NaN NaN NaN NaN
15  NaN NaN NaN NaN
16  NaN NaN NaN NaN
17  NaN NaN NaN NaN
18  NaN NaN NaN NaN
19  NaN NaN NaN NaN
20  NaN NaN NaN NaN
21  NaN NaN NaN NaN
22  NaN NaN NaN NaN
23  NaN NaN NaN NaN
24  NaN NaN NaN NaN
25  NaN NaN NaN NaN
26  NaN NaN NaN NaN
27  NaN NaN NaN NaN
28  NaN NaN NaN NaN
29  NaN NaN NaN NaN
..   ..  ..  ..  ..
970 NaN NaN NaN NaN
971 NaN NaN NaN NaN
972 NaN NaN NaN NaN
973 NaN NaN NaN NaN
974 NaN NaN NaN NaN
975 NaN NaN NaN NaN
976 NaN NaN NaN NaN
977 NaN NaN NaN NaN
978 NaN NaN NaN NaN
979 NaN NaN NaN NaN
980 NaN NaN NaN NaN
981 NaN NaN NaN NaN
982 NaN NaN NaN NaN
983 NaN NaN NaN NaN
984 NaN NaN NaN NaN
985 NaN NaN NaN NaN
986 NaN NaN NaN NaN
987 NaN NaN NaN NaN
988 NaN NaN NaN NaN
989 NaN NaN NaN NaN
990 NaN NaN NaN NaN
991 NaN NaN NaN NaN
992 NaN NaN NaN NaN
993 NaN NaN NaN NaN
994 NaN NaN NaN NaN
995 NaN NaN NaN NaN
996 NaN NaN NaN NaN
997 NaN NaN NaN NaN
998 NaN NaN NaN NaN
999 NaN NaN NaN NaN

[1000 rows x 4 columns]

In [100]:
data[(np.abs(data)>3)][22:23]

0   1   2   3
22 NaN NaN NaN NaN

In [105]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
69   1.085350  0.375894 -0.199171  3.217293
95   0.023163  1.194205  0.571301 -3.097877
120  0.198089 -0.411142 -0.431908  3.437974
291  3.469092  0.917337 -0.083423 -0.244393
336 -0.430640  3.305010 -1.152444  0.962516
604  3.180170  2.007388  0.768947  0.703417
867  0.179450  3.244609 -1.048709  0.363111
903 -3.053554  0.459553  0.258640  0.873899

In [116]:
np.sign(data)

0    1    2    3
0    1.0 -1.0  1.0  1.0
1    1.0  1.0  1.0 -1.0
2   -1.0  1.0  1.0 -1.0
3   -1.0 -1.0  1.0 -1.0
4    1.0 -1.0 -1.0 -1.0
5    1.0  1.0  1.0  1.0
6   -1.0  1.0 -1.0  1.0
7   -1.0 -1.0 -1.0 -1.0
8   -1.0  1.0 -1.0 -1.0
9    1.0  1.0 -1.0  1.0
10   1.0 -1.0 -1.0  1.0
11  -1.0  1.0  1.0  1.0
12  -1.0  1.0 -1.0 -1.0
13  -1.0 -1.0  1.0 -1.0
14   1.0 -1.0 -1.0  1.0
15   1.0 -1.0 -1.0 -1.0
16   1.0 -1.0  1.0  1.0
17   1.0 -1.0 -1.0  1.0
18  -1.0 -1.0  1.0  1.0
19   1.0  1.0 -1.0 -1.0
20  -1.0 -1.0  1.0  1.0
21   1.0 -1.0  1.0 -1.0
22  -1.0  1.0  1.0  1.0
23   1.0 -1.0  1.0 -1.0
24   1.0  1.0 -1.0 -1.0
25   1.0  1.0 -1.0 -1.0
26   1.0 -1.0  1.0  1.0
27   1.0  1.0  1.0  1.0
28  -1.0 -1.0 -1.0 -1.0
29   1.0 -1.0 -1.0  1.0
..   ...  ...  ...  ...
970 -1.0 -1.0  1.0  1.0
971  1.0  1.0  1.0  1.0
972 -1.0 -1.0  1.0  1.0
973 -1.0 -1.0 -1.0  1.0
974  1.0 -1.0  1.0  1.0
975  1.0  1.0  1.0  1.0
976  1.0 -1.0 -1.0 -1.0
977 -1.0 -1.0 -1.0 -1.0
978 -1.0  1.0 -1.0  1.0
979 -1.0  1.0  1.0 -1.0
980  1.0  1.0  1.0  1.0
981 -1.0 -1.0  1.0 -1.0
982  1.0  1.0 -1.0 -1.0
983  1.0 -1.0 -1.0 -1.0
984  1.0 -1.0 -1.0 -1.0
985  1.0  1.0 -1.0  1.0
986  1.0 -1.0  1.0  1.0
987  1.0  1.0  1.0 -1.0
988 -1.0 -1.0  1.0 -1.0
989 -1.0  1.0  1.0 -1.0
990  1.0  1.0  1.0  1.0
991 -1.0 -1.0  1.0  1.0
992 -1.0 -1.0 -1.0  1.0
993  1.0 -1.0  1.0  1.0
994  1.0 -1.0 -1.0  1.0
995  1.0  1.0  1.0  1.0
996 -1.0 -1.0  1.0  1.0
997  1.0 -1.0  1.0  1.0
998 -1.0 -1.0 -1.0  1.0
999  1.0 -1.0 -1.0  1.0

[1000 rows x 4 columns]